"""Convert `astro dev parse` output into the verifier's failure JSON.

`astro dev parse` builds the project's Docker image (the real target Runtime +
the project's requirements) and runs Astro's DAG-integrity pytest suite inside
it — one `test_file_imports[<relative path>]` per discovered DAG file. This
script turns that text output into the same JSON shape import_check.py emits,
so compare_failures.py can diff a target run against a baseline run unchanged.

Argv: path to the captured `astro dev parse` output (stdout+stderr combined).
Env out:
  IMPORT_JSON  when set, {"checked": N, "failures": [{"path", "exc_class", "msg"}]}

Exit codes (verify.sh keys on these):
  0  image built, all DAG files import
  3  image built, at least one DAG file failed to import
  4  the image itself failed to build (dependency resolution, Dockerfile error)
  5  pytest died during COLLECTION — the DAGs were never tested. Field case:
     the repo's committed .astro/test_dag_integrity_default.py (generated by
     an older astro CLI) calls DagBag with an argument the target Airflow
     removed, so the harness itself is incompatible with the target.
  2  output not recognized as an `astro dev parse` run (infra; caller treats
     like an env failure, never like a code verdict)
"""

from __future__ import annotations

import json
import os
import re
import sys

from report_fmt import failure

BUILD_MARKER = "an error was encountered while building the image"
_COLLECTED = re.compile(r"^collected (\d+) items?")
# pytest's closing summary line — its presence is the evidence the run FINISHED.
# A timeout kill mid-run leaves "collected N items" with no summary; that must
# never read as a verdict (a green "all N import cleanly" over untested DAGs).
_SUMMARY = re.compile(r"^=+ .*\b(passed|failed|error|no tests ran)\b.* in [0-9.]+s? =+", re.MULTILINE)
_FAILED_LINE = re.compile(r"^FAILED .*::test_file_imports\[(?P<path>[^\]]+)\]")
_EXC_HEAD = re.compile(r"^E\s+Exception: (?P<path>\S+) failed to import with message")
_EXC_CLASS = re.compile(r"^([A-Za-z_][A-Za-z0-9_.]*(?:Error|Exception|Warning))\b")
_CLEAN = "No errors detected in your DAGs"


def parse_output(text: str) -> tuple[int, dict]:
    if BUILD_MARKER in text:
        return 4, {"checked": 0, "failures": []}
    if "error during collection" in text or "errors during collection" in text:
        # Surface the terse cause (e.g. "TypeError: DagBag.__init__() got...")
        # from pytest's short summary so the caller can show why.
        cause = ""
        for line in text.splitlines():
            if line.startswith("ERROR ") and " - " in line:
                cause = line.split(" - ", 1)[1].strip()
                break
        return 5, {"checked": 0, "failures": [], "collection_error": cause}

    lines = text.splitlines()
    checked = 0
    for line in lines:
        m = _COLLECTED.match(line.strip())
        if m:
            checked = int(m.group(1))

    failures: dict[str, dict] = {}
    i = 0
    while i < len(lines):
        m = _EXC_HEAD.match(lines[i])
        if not m:
            i += 1
            continue
        path = m.group("path")
        # The rv (DagBag's import error text) follows on the E-continuation
        # lines; the last one is the terse `SomeError: ...` line, mirroring
        # import_check's last-traceback-line convention.
        block: list[str] = []
        i += 1
        while i < len(lines) and lines[i].startswith("E"):
            content = lines[i][1:].strip()
            if content:
                block.append(content)
            i += 1
        msg = block[-1] if block else "failed to import (see the CI log for the traceback)"
        cm = _EXC_CLASS.match(msg)
        failures[path] = failure(path, cm.group(1).rsplit(".", 1)[-1] if cm else "", msg)
    # The short-summary FAILED lines are the authoritative list of failing
    # files; make sure each has an entry even if its E-block wasn't matched.
    for line in lines:
        m = _FAILED_LINE.match(line.strip())
        if m and m.group("path") not in failures:
            failures[m.group("path")] = failure(
                m.group("path"), "", "failed to import (see the CI log for the traceback)")

    # A verdict requires evidence the run COMPLETED, not merely started:
    # the astro clean marker or pytest's closing summary line. "collected N
    # items" alone is what a timeout kill leaves behind.
    completed = _CLEAN in text or _SUMMARY.search(text) is not None
    if not completed:
        return 2, {"checked": 0, "failures": []}
    return (3 if failures else 0), {"checked": checked, "failures": sorted(
        failures.values(), key=lambda f: f["path"])}


def main() -> int:
    with open(sys.argv[1], encoding="utf-8", errors="replace") as fh:
        text = fh.read()
    rc, result = parse_output(text)
    json_path = os.environ.get("IMPORT_JSON")
    if json_path:
        with open(json_path, "w", encoding="utf-8") as fh:
            json.dump(result, fh, indent=2)
    return rc


if __name__ == "__main__":
    sys.exit(main())
